export const BASE_CLICK_POWER = 1;
export const BASE_JIGGLE_DAMP = 0.5;

export const BASE_COST_UPGRADE_MIN_JIGGLE = 300;
export const BASE_COST_UPGRADE_CLICK_POWER = 500;
export const BASE_COST_UPGRADE_JIGGLE_DAMP = 1000;
